import RFB from './vendor/core/rfb.js';
const node=new URL(location.href).searchParams.get('node');
const names={'gpu-node-a':'5090 GPU 服务器','gpu-node-b':'4090-1 GPU 服务器','gpu-node-c':'4090-2 GPU 服务器'};
const $=id=>document.getElementById(id);
let ticket=null,rfb=null,stopping=false,connecting=false,retries=0,heartbeat=null,statusTimer=null;
const errors={desktop_starting:'独立桌面正在启动，请稍后重试。',desktop_start_failed:'独立桌面未能启动，请联系管理员检查。',login_required:'网站登录已失效，请返回首页重新登录。',invalid_credentials:'服务器账号或密码不正确，或该账号已停用。',rate_limited:'验证失败次数过多，请在 10 分钟后重试。',occupied:'已有其他远程连接正在使用。',desktop_unavailable:'暂时没有可用的桌面会话。',node_unavailable:'服务器远程桌面服务暂时离线。',lease_expired:'连接占用已释放，请重新验证账号。',invalid_origin:'请求来源验证失败，请刷新页面。',};
async function api(path,body){const res=await fetch('/desktop/api/'+path,{method:body?'POST':'GET',credentials:'same-origin',cache:'no-store',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});let data={};try{data=await res.json()}catch(_){}if(!res.ok)throw Object.assign(new Error(errors[data.error]||`请求失败 (${res.status})`),{code:data.error,status:res.status,account:data.account});return data;}
function showError(error){$('message').textContent=error.message+(error.account?` 当前账号：${error.account}`:'');$('message').hidden=false;}
async function refreshStatus(){if(!names[node])return;try{const data=await api('status');const s=data.nodes[node];$('connect').disabled=connecting||!s?.online||!s.available||s.occupied;if(ticket){$('occupancy').textContent=`当前远程账号：${s.account||'正在连接'}`;return;}if(!s?.online){$('occupancy').textContent='远程桌面服务暂时离线。';$('connection-state').textContent='离线';}else if(!s.available){$('occupancy').textContent=errors[s.error]||'桌面暂不可用';$('connection-state').textContent='待维护';}else if(s.occupied){$('occupancy').textContent=`正在被 ${s.account} 占用${s.connected?'（已连接）':'（正在连接或重连）'}，请等待对方释放。`;$('connection-state').textContent=`占用：${s.account}`;}else{$('occupancy').textContent='当前无人远程占用。验证后直接进入你的独立桌面，已有会话会自动恢复。';$('connection-state').textContent='可连接';}}catch(e){$('connect').disabled=true;showError(e);}}
function applyQuality(){if(!rfb)return;const levels={smooth:[4,2],balanced:[6,2],sharp:[8,3]};[rfb.qualityLevel,rfb.compressionLevel]=levels[$('quality').value];}
async function startRfb(){if(!ticket||stopping)return;$('connection-state').textContent=retries?'桌面切换中，正在重连…':'正在建立桌面连接…';const ws=`${location.protocol==='https:'?'wss:':'ws:'}//${location.host}/desktop/ws/${encodeURIComponent(node)}?ticket=${encodeURIComponent(ticket)}`;const conn=new RFB($('screen'),ws,{shared:false});rfb=conn;conn.scaleViewport=true;conn.resizeSession=false;applyQuality();conn.addEventListener('connect',()=>{if(rfb!==conn)return;retries=0;$('connection-state').textContent=`已连接 · ${$('desktop-username').value}`;$('access-panel').hidden=true;$('disconnect').disabled=false;$('end-session').disabled=false;$('ctrl-alt-del').disabled=false;});conn.addEventListener('disconnect',()=>{if(rfb!==conn||stopping||!ticket)return;$('ctrl-alt-del').disabled=true;if(retries++<10){setTimeout(()=>void startRfb(),1500)}else{showError(new Error('桌面连接中断，请重新验证连接。'));void release();}});conn.addEventListener('securityfailure',()=>showError(new Error('桌面握手失败，请重新连接。')));}
async function release(end=false){if(stopping)return;stopping=true;$('connection-state').textContent=end?'正在结束桌面…':'正在断开…';const current=ticket;ticket=null;clearInterval(heartbeat);if(rfb){rfb.disconnect();rfb=null;}$('screen').replaceChildren();if(current){try{await api(`${node}/${end?'end':'release'}`,{ticket:current})}catch(e){showError(e);}}$('access-panel').hidden=false;$('disconnect').disabled=true;$('end-session').disabled=true;$('ctrl-alt-del').disabled=true;connecting=false;stopping=false;await refreshStatus();}
$('connect-form').addEventListener('submit',async event=>{event.preventDefault();if(connecting||ticket)return;connecting=true;$('connect').disabled=true;$('message').hidden=true;$('connection-state').textContent='正在验证并启动独立桌面…';try{const username=$('desktop-username').value.trim();const password=$('desktop-password').value;$('desktop-password').value='';const data=await api(`${node}/acquire`,{username,password});ticket=data.ticket;retries=0;$('disconnect').disabled=false;heartbeat=setInterval(async()=>{if(!ticket)return;try{await api(`${node}/heartbeat`,{ticket})}catch(e){showError(e);await release();}},15000);await startRfb();}catch(e){showError(e);connecting=false;await refreshStatus();}});
$('disconnect').addEventListener('click',()=>void release());$('end-session').addEventListener('click',()=>{if(confirm('结束当前独立桌面会关闭其中全部应用，未保存内容将丢失。SSH 任务不会受影响。确定结束吗？'))void release(true);});$('quality').addEventListener('change',applyQuality);$('ctrl-alt-del').addEventListener('click',()=>rfb?.sendCtrlAltDel());$('fullscreen').addEventListener('click',()=>{if(document.fullscreenElement)void document.exitFullscreen();else void $('screen').requestFullscreen();});
window.addEventListener('pagehide',()=>{if(ticket)navigator.sendBeacon(`/desktop/api/${node}/release`,new Blob([JSON.stringify({ticket})],{type:'application/json'}));});
window.addEventListener('storage',event=>{if(event.key==='lab-desktop-logout')void release();});
if(!names[node]){$('occupancy').textContent='无效的服务器，请从状态首页进入。';$('connect-form').hidden=true;}else{$('node-name').textContent=names[node];document.title=`远程桌面 · ${names[node]}`;void refreshStatus();statusTimer=setInterval(()=>void refreshStatus(),10000);}
